name: con_cidadania
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  device_preview: ^1.2.0
  get_it: ^9.0.5
  email_validator: ^3.0.0
  provider: ^6.1.0
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  image_picker: ^1.0.4
  intl: ^0.20.2
  file_picker: ^10.3.3
  universal_io: ^2.2.2
  path_provider: ^2.1.5
  url_launcher: ^6.3.2
  http: ^1.5.0
  pdf: ^3.11.3        # Para a criação dos documentos PDF
  printing: ^5.12.0   # Para a visualização do PDF no Web

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  firebase_auth_web: ^6.1.0 # Importante para web
  firebase_storage_web: ^3.10.13 # Importante para web
  cloud_firestore_web: ^5.1.0 # Importante para web

flutter:
  uses-material-design: true
  assets:
  - assets/images/
